# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d26e08e44ce773aef829bb41c21bca56846c3ac00bca1752b6cfb428b9ab88eff8625044903416ce4b184f94266f6953763e49b96763ab286b5d59a675252fd

test:
  secret_key_base: 71407a33211bd1cf3b3a59eeacb6555223e690c0554968433fa4a3876e32baf865dc0e0209e3bcd314cba8b02d3e69b49c800fec6686de0bc4f39ba75286b2c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
